version: '2'

services:
    web:
        build: .
        volumes:
            - ./nginx-config/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#            - ./nginx-config/:/etc/nginx/
            - ./nginx-html:/usr/share/nginx/html
            - ./nginx-log:/var/log/nginx
        ports:
            - 80:80

